name: Update FireAlarms Page

on:
  schedule:
    - cron: '0 4 * * *'  # Runs daily at 04:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Dependencies
        run: pip install feedparser waybackpy jinja2

      - name: Generate FireAlarms HTML
        run: python generate_firenews.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add firealarms.html fire_archive.json
          git commit -m "Daily update of firealarms.html"
          git push
